name: Deploy on push multiple jobs
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: |
                  echo "Executing lint"
                  npm run lint
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run test
              run: |
                  echo "Executing test"
                  npm test
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run build
              run: |
                  echo "Executing build"
                  npm run build
                  echo "Deploying..."