name: Deploy on push single job
on: push
jobs:
    full_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: |
                  echo "Executing lint"
                  npm run lint
            - name: Run test
              run: |
                  echo "Executing test"
                  npm test
            - name: Run test
              run: |
                  echo "Executing build"
                  npm run build
                  echo "Deploying..."